/**
 * Cloudflare provisioner — generates wrangler.toml config. No API calls.
 */

import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { Provisioner, ProvisionContext, ProvisionEmitter, ProvisionResult, CreatedResource } from './types.js';

function slugify(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9-]/g, '-').replace(/-+/g, '-').slice(0, 40);
}

export const cloudflareProvisioner: Provisioner = {
  async validate(ctx: ProvisionContext): Promise<string[]> {
    const errors: string[] = [];
    if (!ctx.projectDir) errors.push('Project directory is required');
    return errors;
  },

  async provision(ctx: ProvisionContext, emit: ProvisionEmitter): Promise<ProvisionResult> {
    const files: string[] = [];
    const slug = slugify(ctx.projectName);

    emit({ step: 'cloudflare-config', status: 'started', message: 'Generating wrangler.toml' });
    try {
      const config = `# wrangler.toml — Cloudflare Workers/Pages configuration
# Generated by VoidForge
# Deploy with: npx wrangler deploy

name = "${slug}"
main = "src/index.ts"
compatibility_date = "${new Date().toISOString().slice(0, 10)}"

# Uncomment for Pages:
# pages_build_output_dir = "./dist"

# Uncomment to add D1 database:
# [[d1_databases]]
# binding = "DB"
# database_name = "${slug}-db"
# database_id = "<your-d1-database-id>"

# Uncomment to add R2 storage:
# [[r2_buckets]]
# binding = "BUCKET"
# bucket_name = "${slug}-bucket"

[vars]
ENVIRONMENT = "production"
`;

      await writeFile(join(ctx.projectDir, 'wrangler.toml'), config, 'utf-8');
      files.push('wrangler.toml');
      emit({
        step: 'cloudflare-config', status: 'done',
        message: 'Generated wrangler.toml — deploy with `npx wrangler deploy` when your app is built',
      });
    } catch (err) {
      emit({ step: 'cloudflare-config', status: 'error', message: 'Failed to write wrangler.toml', detail: (err as Error).message });
      return { success: false, resources: [], outputs: {}, files, error: (err as Error).message };
    }

    return { success: true, resources: [], outputs: {}, files };
  },

  async cleanup(_resources: CreatedResource[], _credentials: Record<string, string>): Promise<void> {
    // Config-only
  },
};
