/**
 * Railway provisioner — generates railway.toml config. No API calls.
 */

import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { Provisioner, ProvisionContext, ProvisionEmitter, ProvisionResult, CreatedResource } from './types.js';

export const railwayProvisioner: Provisioner = {
  async validate(ctx: ProvisionContext): Promise<string[]> {
    const errors: string[] = [];
    if (!ctx.projectDir) errors.push('Project directory is required');
    return errors;
  },

  async provision(ctx: ProvisionContext, emit: ProvisionEmitter): Promise<ProvisionResult> {
    const files: string[] = [];
    const framework = ctx.framework || 'express';

    emit({ step: 'railway-config', status: 'started', message: 'Generating railway.toml' });
    try {
      const startCommand = framework === 'next.js'
        ? 'npm run start'
        : framework === 'django'
          ? 'gunicorn config.wsgi:application --bind 0.0.0.0:$PORT'
          : 'node dist/index.js';

      const buildCommand = framework === 'django'
        ? 'pip install -r requirements.txt && python manage.py collectstatic --noinput'
        : 'npm ci && npm run build';

      const config = `# railway.toml — Railway deployment configuration
# Generated by VoidForge
# Deploy with: railway up

[build]
builder = "nixpacks"
buildCommand = "${buildCommand}"

[deploy]
startCommand = "${startCommand}"
healthcheckPath = "/"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
`;

      await writeFile(join(ctx.projectDir, 'railway.toml'), config, 'utf-8');
      files.push('railway.toml');
      emit({
        step: 'railway-config', status: 'done',
        message: 'Generated railway.toml — deploy with `railway up` when your app is built',
      });
    } catch (err) {
      emit({ step: 'railway-config', status: 'error', message: 'Failed to write railway.toml', detail: (err as Error).message });
      return { success: false, resources: [], outputs: {}, files, error: (err as Error).message };
    }

    return { success: true, resources: [], outputs: {}, files };
  },

  async cleanup(_resources: CreatedResource[], _credentials: Record<string, string>): Promise<void> {
    // Config-only
  },
};
