/**
 * Static S3 provisioner — generates deploy script for S3 + CloudFront. No API calls.
 */

import { writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import type { Provisioner, ProvisionContext, ProvisionEmitter, ProvisionResult, CreatedResource } from './types.js';

function slugify(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9-]/g, '-').replace(/-+/g, '-').slice(0, 40);
}

export const staticS3Provisioner: Provisioner = {
  async validate(ctx: ProvisionContext): Promise<string[]> {
    const errors: string[] = [];
    if (!ctx.projectDir) errors.push('Project directory is required');
    return errors;
  },

  async provision(ctx: ProvisionContext, emit: ProvisionEmitter): Promise<ProvisionResult> {
    const files: string[] = [];
    const slug = slugify(ctx.projectName);

    emit({ step: 's3-config', status: 'started', message: 'Generating S3 deploy script' });
    try {
      const infraDir = join(ctx.projectDir, 'infra');
      await mkdir(infraDir, { recursive: true });

      const deployScript = `#!/usr/bin/env bash
# deploy-s3.sh — Deploy static site to S3 + CloudFront
# Generated by VoidForge
# Requires: AWS CLI configured with credentials
set -euo pipefail

BUCKET="\${S3_BUCKET:-${slug}}"
DISTRIBUTION_ID="\${CF_DISTRIBUTION_ID:-}"
BUILD_DIR="\${BUILD_DIR:-dist}"

echo "=== Deploying to S3 bucket: $BUCKET ==="

# Sync build output to S3
aws s3 sync "$BUILD_DIR" "s3://$BUCKET" \\
  --delete \\
  --cache-control "public, max-age=31536000, immutable" \\
  --exclude "*.html" \\
  --exclude "sw.js" \\
  --exclude "manifest.json"

# HTML and service worker files with short cache
aws s3 sync "$BUILD_DIR" "s3://$BUCKET" \\
  --cache-control "public, max-age=0, must-revalidate" \\
  --exclude '*' \\
  --include "*.html" \\
  --include "sw.js" \\
  --include "manifest.json"

# Invalidate CloudFront cache (if configured)
if [ -n "$DISTRIBUTION_ID" ]; then
  echo "Invalidating CloudFront cache..."
  aws cloudfront create-invalidation \\
    --distribution-id "$DISTRIBUTION_ID" \\
    --paths "/*"
fi

echo ""
echo "=== Deploy complete ==="
echo "Site: https://$BUCKET.s3.amazonaws.com (or your CloudFront domain)"
`;

      await writeFile(join(infraDir, 'deploy-s3.sh'), deployScript, { mode: 0o755 });
      files.push('infra/deploy-s3.sh');

      emit({
        step: 's3-config', status: 'done',
        message: 'Generated infra/deploy-s3.sh — create an S3 bucket, then run the script to deploy',
      });
    } catch (err) {
      emit({ step: 's3-config', status: 'error', message: 'Failed to generate S3 deploy script', detail: (err as Error).message });
      return { success: false, resources: [], outputs: {}, files, error: (err as Error).message };
    }

    return { success: true, resources: [], outputs: {}, files };
  },

  async cleanup(_resources: CreatedResource[], _credentials: Record<string, string>): Promise<void> {
    // Config-only
  },
};
