/**
 * Template: Caddyfile — reverse proxy + automatic HTTPS.
 * Written to projectDir/infra/Caddyfile
 */

interface CaddyfileOptions {
  framework: string;
}

export function generateCaddyfile(opts: CaddyfileOptions): string {
  const port = opts.framework === 'django' ? '8000' : '3000';

  return `# Caddyfile — Reverse proxy with automatic HTTPS
# Generated by VoidForge
#
# Usage:
#   1. Replace :80 with your domain (e.g. example.com)
#   2. Copy to server: scp Caddyfile user@host:/etc/caddy/Caddyfile
#   3. Reload: sudo systemctl reload caddy
#
# Caddy auto-provisions HTTPS certificates via Let's Encrypt.

:80 {
    reverse_proxy localhost:${port}

    # Security headers
    header {
        X-Content-Type-Options nosniff
        X-Frame-Options DENY
        Referrer-Policy strict-origin-when-cross-origin
        -Server
    }

    # Gzip compression
    encode gzip

    # Access logs
    log {
        output file /var/log/caddy/access.log
    }
}
`;
}
