/**
 * Template: deploy.sh — rsync + PM2 reload for VPS deploys.
 * Written to projectDir/infra/deploy.sh
 */

interface DeployScriptOptions {
  framework: string;
}

export function generateDeployScript(opts: DeployScriptOptions): string {
  const isNode = ['next.js', 'express'].includes(opts.framework) || !opts.framework;
  const isDjango = opts.framework === 'django';

  let deployCommands: string;
  if (isNode) {
    deployCommands = `
# Install dependencies
ssh $SSH_OPTS $SSH_USER@$SSH_HOST "cd $APP_DIR && npm ci --production --ignore-scripts"

# Restart with PM2
ssh $SSH_OPTS $SSH_USER@$SSH_HOST "cd $APP_DIR && pm2 startOrRestart ecosystem.config.js --env production"
ssh $SSH_OPTS $SSH_USER@$SSH_HOST "pm2 save"`;
  } else if (isDjango) {
    deployCommands = `
# Install dependencies
ssh $SSH_OPTS $SSH_USER@$SSH_HOST "cd $APP_DIR && pip3.12 install -r requirements.txt"

# Run migrations
ssh $SSH_OPTS $SSH_USER@$SSH_HOST "cd $APP_DIR && python3.12 manage.py migrate --noinput"

# Collect static files
ssh $SSH_OPTS $SSH_USER@$SSH_HOST "cd $APP_DIR && python3.12 manage.py collectstatic --noinput"

# Restart
ssh $SSH_OPTS $SSH_USER@$SSH_HOST "supervisorctl restart app"`;
  } else {
    deployCommands = `
# Install dependencies and restart
ssh $SSH_OPTS $SSH_USER@$SSH_HOST "cd $APP_DIR && bundle install --deployment --without development test"
ssh $SSH_OPTS $SSH_USER@$SSH_HOST "cd $APP_DIR && RAILS_ENV=production bundle exec rails db:migrate"
ssh $SSH_OPTS $SSH_USER@$SSH_HOST "cd $APP_DIR && touch tmp/restart.txt"`;
  }

  return `#!/usr/bin/env bash
# deploy.sh — Deploy to VPS via rsync + restart
# Generated by VoidForge. Reads config from .env
set -euo pipefail

# Load environment
if [ -f .env ]; then
  set -a
  source .env
  set +a
fi

SSH_HOST="\${SSH_HOST:?Set SSH_HOST in .env}"
SSH_USER="\${SSH_USER:-ec2-user}"
SSH_KEY="\${SSH_KEY_PATH:-.ssh/deploy-key.pem}"
APP_DIR="/opt/app"

SSH_OPTS="-i $SSH_KEY -o StrictHostKeyChecking=no"

echo "=== Deploying to $SSH_HOST ==="

# Sync files (exclude dev/build artifacts)
rsync -avz --delete \\
  --exclude node_modules \\
  --exclude .git \\
  --exclude .env \\
  --exclude logs \\
  --exclude .ssh \\
  --exclude infra \\
  --exclude coverage \\
  -e "ssh $SSH_OPTS" \\
  ./ "$SSH_USER@$SSH_HOST:$APP_DIR/"
${deployCommands}

echo ""
echo "=== Deploy complete ==="
echo "App running at http://$SSH_HOST"
`;
}
