/**
 * Template: provision.sh — idempotent server setup for VPS.
 * Written to projectDir/infra/provision.sh
 */

interface ProvisionScriptOptions {
  framework: string;
  database: string;
  cache: string;
}

export function generateProvisionScript(opts: ProvisionScriptOptions): string {
  const nodeSetup = ['next.js', 'express'].includes(opts.framework) || !opts.framework;
  const pythonSetup = opts.framework === 'django';
  const rubySetup = opts.framework === 'rails';

  let runtimeInstall = '';
  if (nodeSetup) {
    runtimeInstall = `
# Install Node.js 20.x
if ! command -v node &>/dev/null; then
  echo "Installing Node.js..."
  curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -
  dnf install -y nodejs
fi
echo "Node.js $(node --version)"

# Install PM2 globally
if ! command -v pm2 &>/dev/null; then
  npm install -g pm2
fi
echo "PM2 $(pm2 --version)"`;
  } else if (pythonSetup) {
    runtimeInstall = `
# Install Python 3.12
if ! command -v python3.12 &>/dev/null; then
  echo "Installing Python 3.12..."
  dnf install -y python3.12 python3.12-pip
fi
echo "Python $(python3.12 --version)"

# Install gunicorn + supervisor
pip3.12 install --quiet gunicorn supervisor`;
  } else if (rubySetup) {
    runtimeInstall = `
# Install Ruby
if ! command -v ruby &>/dev/null; then
  echo "Installing Ruby..."
  dnf install -y ruby ruby-devel
fi
echo "Ruby $(ruby --version)"

# Install bundler
gem install bundler --no-document`;
  }

  return `#!/usr/bin/env bash
# provision.sh — Idempotent VPS setup
# Generated by VoidForge. Safe to re-run.
set -euo pipefail

echo "=== VoidForge VPS Provisioning ==="

# Update system
echo "Updating packages..."
dnf update -y -q

# Install essentials
dnf install -y -q git curl wget tar unzip
${runtimeInstall}

# Install Caddy (reverse proxy + auto HTTPS)
if ! command -v caddy &>/dev/null; then
  echo "Installing Caddy..."
  dnf install -y 'dnf-command(copr)'
  dnf copr enable -y @caddy/caddy
  dnf install -y caddy
  systemctl enable caddy
fi
echo "Caddy $(caddy version)"

# Create app directory
APP_DIR="/opt/app"
mkdir -p "$APP_DIR"

# Create app user if not exists
if ! id -u appuser &>/dev/null; then
  useradd --system --home-dir "$APP_DIR" --shell /bin/bash appuser
fi
chown -R appuser:appuser "$APP_DIR"

# Set up firewall
if command -v firewall-cmd &>/dev/null; then
  firewall-cmd --permanent --add-service=http 2>/dev/null || true
  firewall-cmd --permanent --add-service=https 2>/dev/null || true
  firewall-cmd --reload 2>/dev/null || true
fi

echo ""
echo "=== Provisioning complete ==="
echo "App directory: $APP_DIR"
echo "App user: appuser"
echo "Next: run deploy.sh to deploy your app"
`;
}
