/**
 * Template: rollback.sh — quick rollback to previous deploy.
 * Written to projectDir/infra/rollback.sh
 */

interface RollbackScriptOptions {
  framework: string;
}

export function generateRollbackScript(opts: RollbackScriptOptions): string {
  const isNode = ['next.js', 'express'].includes(opts.framework) || !opts.framework;
  const isDjango = opts.framework === 'django';

  let restartCommands: string;
  if (isNode) {
    restartCommands = `
# Reinstall dependencies and restart
ssh $SSH_OPTS $SSH_USER@$SSH_HOST "cd $APP_DIR && npm ci --production --ignore-scripts"
ssh $SSH_OPTS $SSH_USER@$SSH_HOST "cd $APP_DIR && pm2 startOrRestart ecosystem.config.js --env production"`;
  } else if (isDjango) {
    restartCommands = `
# Reinstall dependencies and restart
ssh $SSH_OPTS $SSH_USER@$SSH_HOST "cd $APP_DIR && pip3.12 install -r requirements.txt"
ssh $SSH_OPTS $SSH_USER@$SSH_HOST "cd $APP_DIR && python3.12 manage.py migrate --noinput"
ssh $SSH_OPTS $SSH_USER@$SSH_HOST "supervisorctl restart app"`;
  } else {
    restartCommands = `
# Reinstall dependencies and restart
ssh $SSH_OPTS $SSH_USER@$SSH_HOST "cd $APP_DIR && bundle install --deployment --without development test"
ssh $SSH_OPTS $SSH_USER@$SSH_HOST "cd $APP_DIR && RAILS_ENV=production bundle exec rails db:migrate"
ssh $SSH_OPTS $SSH_USER@$SSH_HOST "cd $APP_DIR && touch tmp/restart.txt"`;
  }

  return `#!/usr/bin/env bash
# rollback.sh — Rollback to previous deployment
# Generated by VoidForge. Uses git to revert.
set -euo pipefail

# Load environment
if [ -f .env ]; then
  set -a
  source .env
  set +a
fi

SSH_HOST="\${SSH_HOST:?Set SSH_HOST in .env}"
SSH_USER="\${SSH_USER:-ec2-user}"
SSH_KEY="\${SSH_KEY_PATH:-.ssh/deploy-key.pem}"
APP_DIR="/opt/app"

SSH_OPTS="-i $SSH_KEY -o StrictHostKeyChecking=no"

echo "=== Rolling back on $SSH_HOST ==="

# Revert to previous commit
ssh $SSH_OPTS $SSH_USER@$SSH_HOST "cd $APP_DIR && git checkout HEAD~1"
${restartCommands}

echo ""
echo "=== Rollback complete ==="
echo "Run 'deploy.sh' to re-deploy the latest version."
`;
}
